name: MLOps CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Create and Activate Virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint pytest  # Install pylint and pytest

      - name: Check installed packages
        run: |
          source venv/bin/activate
          pip list | grep mlflow  # Check if mlflow is installed

      - name: Run Linter
        run: |
          source venv/bin/activate
          pylint src/train.py src/test.py

      - name: Run Tests
        run: |
          source venv/bin/activate
          pytest src/test.py

      - name: Train Model
        run: |
          source venv/bin/activate
          python src/train.py  # This step will save the model in the models folder

      - name: Debug Build Context
        run: |
          echo "Debugging build context:"
          ls -R

      - name: Log Model with MLflow
        run: |
          source venv/bin/activate
          mlflow run . --experiment-name "my_experiment" --run-name "run_$(date +%Y%m%d%H%M%S)"

      - name: Deploy Model
        run: |
          source venv/bin/activate
          docker build -t my-ml-model .
          docker run -p 5000:5000 my-ml-model
