name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Linter
        run: pylint train_model.py

      - name: Run Tests
        run: pytest test_model.py

      - name: Deploy Model
        run: |
          docker build -t my-ml-model .
          docker run -p 5000:5000 my-ml-model
